directory: /media/music
library: ~/docs/musiclibrary.db
import:
        move: yes
        incremental: yes
plugins: discogs chroma ftintitle fetchart
paths:
    default: %lower{$albumartist/$album%aunique{}/$track $title}
    comp: %lower{compilations/$album%aunique{}/$track $title}
fetchart:
        minwidth: 1000
        maxwidth: 1200
replace:
        '[ ]': _
asciify_paths: yes
