#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ytd="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	bi="beet import dl/complete"\
	v="nvim"
	xm="sudo mount UUID=9b253b00-e0ed-4fa7-854a-4d911599d8ca /media"
	g="git" \
	trem="transmission-remote" \
	ytv="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"

alias \
	bf="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/files" \
	bd="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/directories" \
	bw="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/bookmarks" \
	cfa="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc" \
	cfz="nvim $ZDOTDIR/.zshrc" \
	cfv="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/init.vim" \
	cft="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/.tmux.conf" \
	cfm="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/mutt/muttrc" \
	cfx="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources" \
	cfu="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls" \
	cfn="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/config" \
	cfmb="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/ncmpcpp/bindings" \
	cfmc="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/ncmpcpp/config" \
	cfk="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/sxhkd/sxhkdrc" \
	cfi="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/i3/config" \
	cfb="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/i3blocks/config" \
	cff="nvim ${XDG_CONFIG_HOME:-$HOME/.config}/fontconfig/fonts.conf"
